routes/web.php
<?php

use App\Http\Controllers\FrontController;
use App\Campaign;
use App\Client;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// temp putting this up here so it frickin works
Route::get('report/export/{report_id}', 'CampaignController@reportExport');
Route::get('report/{report_id}', 'CampaignController@report');

$zoos_routes = function () {

    // require functions
    $project_functions = dirname(__FILE__) . '/../public/assets/zoos-victoria_renew/functions.php';
    if(is_file($project_functions)) require_once($project_functions);

    $client_slug = 'zoos-victoria';
    $campaign_slug = 'renew';

    Route::post('send/{hash}', function ($hash) {
        $send = sendToFriends();
        return response()->json(true);
    });

    Route::post('video', function () {
        $videoUrl = renderVideo();
        return response()->json($videoUrl);
    });

    Route::get('/', function () use ($client_slug, $campaign_slug) {
        $front = new FrontController;
        return $front->primaryLanding($client_slug, $campaign_slug);
    });

    Route::get('member/{hash}', function ($hash) use ($client_slug, $campaign_slug) {
        $front = new FrontController;
        return $front->primaryLanding($client_slug, $campaign_slug, $hash);
    });

};

// ZOOS VIC ROUTES
Route::group(['domain' => 'zoos.vhx.host'], $zoos_routes);
Route::group(['domain' => 'zoos.mmrserver.com'], $zoos_routes);
Route::group(['domain' => 'renewforthezoo.org.au'], $zoos_routes);


// FRONT/LANDING (public)

//Route::auth();
Auth::routes();

Route::get('pw/{pw}', function ($pw) {
    return $pw . ':<br>' . '<textarea style="width:100%;" rows="50">' . bcrypt($pw) . '</textarea>';
});

Route::get('/{client}/{campaign}/', 'FrontController@primaryLanding');
Route::get('/{client}/{campaign}/register', 'FrontController@primaryLanding');
Route::get('/{client}/{campaign}/update/{hash}', 'FrontController@primaryLanding');
Route::get('/{client}/{campaign}/update/{hash}/{sendout}', 'FrontController@primaryLanding');
Route::post('/{client}/{campaign}/update/{hash}', 'FrontController@primaryProcess');
Route::get('/{client}/{campaign}/confirm/{hash}', 'FrontController@confirm');
Route::get('/{client}/{campaign}/confirm/{hash}/{sendout}', 'FrontController@confirm');
Route::get('/{client}/{campaign}/step-2/{hash}', 'FrontController@secondaryLanding');
Route::post('/{client}/{campaign}/step-2/{hash}', 'FrontController@secondaryProcess');
Route::get('/{client}/{campaign}/thanks/{hash}', 'FrontController@thanks');
Route::get('/{client}/{campaign}/thanks', 'FrontController@thanks');
Route::get('/{client}/{campaign}/update', 'FrontController@primaryLanding');
Route::post('/{client}/{campaign}/update', 'FrontController@primaryProcessNew');
Route::get('/{client}/{campaign}/page/{view}', 'FrontController@page');

// TEST URL
Route::get('/{client}/{campaign}/test/{view_file}/{field_key}/{field_value}', 'FrontController@testData');

Route::post('/link', 'FrontController@createShortUrl');

// DASHBOARD (private)

Route::get('/', 'CampaignController@home');


Route::get('home', 'CampaignController@home');

// campaigns
Route::get('campaigns', 'CampaignController@home');

// campaign responses
Route::get('/responses/send-out/{send_out}', 'HomeController@responses');
Route::get('/responses/field/{field_name}', 'CampaignController@responsesField');
Route::get('/responses/field/{field_name}/send-out/{send_out}', 'CampaignController@responsesField');
Route::get('/responses/compare/{field}', 'CampaignController@responsesCompare');
Route::get('/responses/compare/{field}/send-out/{send_out}', 'HomeController@responses_compare');
Route::get('/responses/record/{record_id}', 'CampaignController@responsesRecord');
Route::get('/responses', 'CampaignController@responses');

// campaign traffic
Route::get('/traffic/send-out/{send_out}', 'HomeController@traffic');
Route::get('/traffic', 'HomeController@traffic');

// campaign data
//Route::get('/data/send-out/{send_out}', 'CampaignController@data');
Route::get('/data', 'CampaignController@data');
Route::get('/data/table', 'CampaignController@dataTable');

// campaigns
Route::get('clients', 'AdminController@clients');
Route::get('client/edit/{client_id}', 'AdminController@editClient');

// reports
Route::get('reports', 'CampaignController@reports');

// admin
//Route::get('/admin/campaigns', 'AdminController@campaigns');

// REST

// campaigns
Route::get('campaign/set/{campaign_id}', 'CampaignController@set');
Route::get('campaign/set/{campaign_id}/{redirect}', 'CampaignController@set');
Route::get('overview/send-out/{send_out}', 'CampaignController@overview');
Route::get('overview', 'CampaignController@overview');
Route::get('overview/{campaign_id}/refresh', 'CampaignController@refreshOverview');
Route::get('responses/{campaign_id}/refresh', 'CampaignController@refreshFieldStats');
Route::get('campaign/tables/create/input/{campaign_id}', 'CampaignController@createInputTable');
Route::get('campaign/tables', 'CampaignController@getTables');
Route::resource('campaign', 'CampaignController');
Route::resource('campaign.fields', 'CampaignFieldController');
Route::resource('campaign.tables', 'CampaignTableController');

Route::get('overview/{campaign_id}/analytics', 'CampaignController@analytics');
Route::get('overview/{campaign_id}/results', 'CampaignController@results');

// sendouts
Route::resource('send-out', 'SendoutController');
Route::get('send-out/campaign/{campaign_id}', 'SendoutController@index');
Route::get('campaign/{campaign_id}/send-outs', 'SendoutController@home');

//Auth
Route::get('/logout', function () {
    Auth::logout();
    return redirect('/login');
});

Route::get('file', 'fileController@index');
 Route::get('save', 'fileController@save');

 

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\StoreCampaign;

use App\Client;
use App\Campaign;
use App\Sendout;
use App\Field;
use App\Nav;
use App\CampaignMonitor;
use App\CM_Campaign;
use App\CMCampaign;
use App\FieldCompare;
use App\CampaignStats;
use App\Report;

use DB;
use Schema;
use Gate;
use Excel;

class CampaignController extends Controller
{
    private $request;

    public function __construct(Request $request)
    {
        $this->middleware('auth');
        $this->request = $request;
    }

    public function home()
    {
        // nav
        $nav = new Nav(false);

        // which campaigns view to show?
        //$campaigns_view = Gate::denies('mmr-admin') ? 'campaigns' : 'admin.campaigns';
        $campaigns_view = 'admin.campaigns';

        // get campaigns
        $campaigns = Campaign::with('client');

        $client = Client::current();

        if(Gate::denies('mmr-admin'))
        {
            $campaigns->where('client_id', $client->id);
        }

        $campaigns = $campaigns->get();

        //dd($campaigns->toArray());

        $totals = [
            'recipients' => 0,
            'emails' => 0,
            'responses' => 0,
        ];

        foreach($campaigns as $campaign)
        {
            $campaign->stats = Campaign::stats($campaign->id, false);

            $totals['recipients'] += $campaign->stats['total_recipients']['total'];
            $totals['emails'] += $campaign->stats['recipients']['total'];
            $totals['responses'] += $campaign->stats['responses']['total'];
        }

        //dd($campaigns->toArray());

        return view($campaigns_view, [
            'nav' => $nav,
            'client' => Client::current(),
            'campaigns' => $campaigns,
            'totals' => $totals,
        ]);
    }

    public function index()
    {
        $campaigns = Campaign::with('client');

        $client = Client::current();
        if($client->id > 1)
        {
            $campaigns->where('client_id', $client->id);
        }

        $campaigns = $campaigns->get();
        return response()->json($campaigns);
    }

    public function set($campaign_id=0, $redirect=false)
    {
        $campaign_id = Campaign::setCurrent($campaign_id);

        if($redirect)
        {
            switch($redirect)
            {
                default : case 'overview' :
                    $redirect_path = 'overview';
                    break;
                case 'edit' :
                    $redirect_path = 'campaign/ ' . $campaign_id . '/edit';
                    break;
            }
        }
        else
        {
            $redirect_path = 'overview';
        }

        return redirect($redirect_path);
    }

    public function refreshOverview($campaign_id)
    {
        $campaign = Campaign::find($campaign_id);
        $cm_campaigns = CMCampaign::where('campaign_id', $campaign_id)->get();

        if($campaign->locked)
        {
            echo "This campaign is locked for updates.";
            exit;
        }

        // CM campaign overview stats
        $campaign_stats = [];
        foreach($cm_campaigns as $cm_campaign) $cm_campaign->syncStats();
        //dd($campaign_stats);

        // CM opens
        $campaign->syncOpens();

        // CM clicks
        $campaign->syncClicks();

        // CM opens
        $campaign->syncResponses();

        // Field stats
        $campaign->syncFieldStats();

        $campaign->touch();

        return redirect('overview');
    }

    public function refreshFieldStats($campaign_id)
    {
        $campaign = Campaign::find($campaign_id);
        $campaign->syncFieldStats();

        return redirect('responses');
    }

    public function overview($send_out_id=false)
    {
        // get current campaign
        $campaign = Campaign::current();

        // if no campain selected, redirect to campaigns screen
        if(! $campaign) return redirect('campaigns');

        // nav
        $nav = new Nav;
        $nav->setItems(Campaign::nav());
        $nav->setActive('overview');

        // set active send out
        if($send_out_id) $nav->setActive("overview.$send_out_id");

        // get campaign overview stats
        $stats = Campaign::stats($campaign->id, $send_out_id);
        //dd($stats);

        // get sendout info
        $send_out = $send_out_id ? Sendout::find($send_out_id) : false;

        // get graph data
        $graph_metric = $this->request->get('graph', 'responses');

        $graph_data = [
            'labels' => [],
            'values' => [],
        ];

        $graph_source = [
            'responses' => CampaignStats::summary($campaign->id, 'responses', false, $send_out_id),
            'opens' => CampaignStats::summary($campaign->id, 'campaign', 'opens', $send_out_id),
            'clicks' => CampaignStats::summary($campaign->id, 'campaign', 'clicks', $send_out_id),
        ];

        foreach($graph_source[$graph_metric] as $metric)
        {
            $graph_data['labels'][] = date('d/m/y', strtotime($metric->date));
            $graph_data['values'][] = $metric->value;
        }

        $view_data = [
            'nav' => $nav,
            'campaign' => $campaign,
            'send_out_title' => $send_out ? $send_out->name : 'All Sendouts',
            'send_out' => $send_out,
            'stats' => $stats,
            'graph_metric' => $graph_metric,
            'graph_source' => $graph_source,
            'graph_data' => $graph_data,
        ];

        //dd($view_data);

        return view('overview', $view_data);
    }

    public function traffic($send_out_id=false)
    {
        // get current campaign
        $campaign = Campaign::current();

        // if no campain selected, redirect to campaigns screen
        if(! $campaign) return redirect('campaigns');

        // nav
        $nav = new Nav;
        $nav->setItems(Campaign::nav());
        $nav->setActive('traffic');

        // set active send out
        if($send_out_id) $nav->setActive("traffic.$send_out_id");

        // get campaign overview stats
        $stats = Campaign::stats($campaign->id, $send_out_id);
        //dd($stats);

        // get sendout info
        $send_out = $send_out_id ? Sendout::find($send_out_id) : false;

        // get graph data
        // $graph_metric = $this->request->get('graph', 'responses');
        //
        // $graph_data = [
        //     'labels' => [],
        //     'values' => [],
        // ];
        //
        // $graph_source = [
        //     'responses' => CampaignStats::summary($campaign->id, 'responses', false, $send_out_id),
        //     'opens' => CampaignStats::summary($campaign->id, 'campaign', 'opens', $send_out_id),
        //     'clicks' => CampaignStats::summary($campaign->id, 'campaign', 'clicks', $send_out_id),
        // ];
        //
        // foreach($graph_source[$graph_metric] as $metric)
        // {
        //     $graph_data['labels'][] = date('d/m/y', strtotime($metric->date));
        //     $graph_data['values'][] = $metric->value;
        // }

        $view_data = [
            'nav' => $nav,
            'campaign' => $campaign,
            'send_out_title' => $send_out ? $send_out->name : 'All Sendouts',
            'send_out' => $send_out,
            'stats' => $stats,
            'graph_metric' => $graph_metric,
            'graph_source' => $graph_source,
            'graph_data' => $graph_data,
        ];

        dd($view_data);

        return view('overview', $view_data);
    }

    public function edit($campaign_id)
    {
        abort_if(Gate::denies('mmr-admin'), 403);

        // nav
        $nav = new Nav;
        $nav->setItems(Campaign::nav());
        $nav->setActive('admin');
        $nav->setActive('admin.edit');

        // get campaign
        $campaign = Campaign::find($campaign_id);

        //$campaign->fields = [];

        return view('campaign.edit', [
            'nav' => $nav,
            'campaign' => $campaign,
            'clients' => Client::all(),
            'tables' => db_campaign_tables($campaign_id),
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('mmr-admin'), 403);

        // nav
        $nav = new Nav;
        $nav->setItems(Campaign::nav());
        $nav->setActive('admin');
        $nav->setActive('admin.create');

        return view('campaign.create', [
            'nav' => $nav,
            'clients' => Client::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCampaign $request)
    {
        abort_if(Gate::denies('mmr-admin'), 403);

        $campaign = new Campaign;
        $campaign->client_id = $request->input('client_id');
        $campaign->name = $request->input('name');
        $campaign->slug = $request->input('slug');
        $campaign->open = ($request->get('open', false) === '1')?'1':'0';
        $campaign->closed_at = '0';
        $campaign->save();

        //return redirect("campaign/$campaign_id/edit");

        return redirect()->route('campaign.edit', ['id' => $campaign->id]);
    }

    public function update($campaign_id, Request $request)
    {
        $campaign = Campaign::find($campaign_id);

        if($campaign)
        {
            $campaign->update($request->except('open', '_token', '_method'));

            // change open state
            if($request->get('open', false) === '1')
            {
                $campaign->open = '1';
                $campaign->closed_at = '0';
            }
            else
            {
                $campaign->open = '0';
                $campaign->closed_at = now();
            }

            $campaign->save();

        }

resources/views/campaign/create.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">Create New Campaign</div>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">

        <h1 class="main__body__title">Create Campaign</h1>

        <div class="main__body__inner form-wrap main__body__inner--grey">

            <div class="form-wrap__inner form-wrap__inner--full-width">

                <form class="form form--large" method="POST" action="{{ route('campaign.store') }}">
                    {!! csrf_field() !!}

                    <div class="form__group form__group--checkbox">
                        <div class="form__checkbox">
                            <label>
                                <input type="checkbox" checked="checked" name="open" value="1" {{ old('open') == '1' ? 'checked' : '' }}>
                                <span></span>
                                Campaign Open
                            </label>
                        </div>
                    </div>

                    <div class="form__group form__select{{ $errors->has('client_id') ? ' form__group--error' : '' }}">
                        <label for="clientField">Client</label>
                        <select name="client_id" id="clientField">
                            <option value="">Not Selected</option>
                            @foreach($clients as $client)
                            <option value="{{ $client->id }}"{{ old('client_id') == $client->id ? ' selected' : '' }}>{{ $client->name }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('client_id'))
                        <div class="form__group__error-message">{{ $errors->first('client_id') }}</div>
                        @endif
                    </div>

                    <div class="form__group{{ $errors->has('name') ? ' form__group--error' : '' }}">
                        <label for="campaignName">Name</label>
                        <input type="text" class="form__input" name="name" value="{{ old('name','Confirm or Update '.date('Y')) }}" id="campaignName">
                        @if ($errors->has('name'))
                        <div class="form__group__error-message">{{ $errors->first('name') }}</div>
                        @endif
                    </div>

                    <div class="form__group{{ $errors->has('slug') ? ' form__group--error' : '' }}">
                        <label for="campaignSlug">Slug</label>
                        <input type="text" class="form__input" name="slug" value="{{ old('slug','confirm-update-'.date('Y')) }}" id="campaignSlug">
                        @if ($errors->has('slug'))
                        <div class="form__group__error-message">{{ $errors->first('slug') }}</div>
                        @endif
                    </div>

                    <div class="form__submit">
                        <button type="submit" class="button button--large">Create Campaign</button>
                    </div>

                </form>

            </div>

        </div>

    </main>

</section>

@endsection

resources/views/campaign/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">{{ $campaign->name }}</div>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">

        <h1 class="main__body__title">Edit Campaign</h1>

        <div class="main__body__inner form-wrap main__body__inner--grey">

            <div class="form-wrap__inner form-wrap__inner--full-width">

                <form class="form form--large" method="POST" action="{{ url('/campaign/' . $campaign->id) }}">
                    {!! csrf_field() !!}
                    <input type="hidden" name="_method" value="PUT">

                    <div class="form__group form__group--checkbox">
                        <div class="form__checkbox">
                            <label>
                                <input type="checkbox" name="open" value="1" {{ old('open', $campaign->open) == '1' ? 'checked' : '' }}>
                                <span></span>
                                Campaign Open
                            </label>
                        </div>
                    </div>

                    <div class="form__group form__select">
                        <label for="clientField">Client</label>
                        <select name="client_id" id="clientField">
                            <option value="">Not Selected</option>
                            @foreach($clients as $client)
                            <option value="{{ $client->id }}"{{ old('client_id', $campaign->client_id) == $client->id ? ' selected' : '' }}>{{ $client->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form__group{{ $errors->has('name') ? ' form__group--error' : '' }}">
                        <label for="campaignName">Name</label>
                        <input type="text" class="form__input" name="name" value="{{ old('name', $campaign->name) }}" id="campaignName">
                        @if ($errors->has('name'))
                        <div class="form__group__error-message">{{ $errors->first('name') }}</div>
                        @endif
                    </div>

                    <div class="form__group{{ $errors->has('slug') ? ' form__group--error' : '' }}">
                        <label for="campaignSlug">Slug</label>
                        <input type="text" class="form__input" name="slug" value="{{ old('slug', $campaign->slug) }}" id="campaignSlug">
                        @if ($errors->has('slug'))
                        <div class="form__group__error-message">{{ $errors->first('slug') }}</div>
                        @endif
                    </div>

                    <div class="form__group form__select">
                        <label for="emailField">Email Field</label>
                        <select name="email_field" id="emailField">
                            <option value="">Not Selected</option>
                            @foreach($campaign->fields(false) as $field)
                            <option value="{{ $field->name }}"{{ old('email_field', $campaign->email_field) == $field->name ? ' selected' : '' }}>{{ $field->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form__group form__select">
                        <label for="mobileField">Mobile Field</label>
                        <select name="mobile_field" id="mobileField">
                            <option value="">Not Selected</option>
                            @foreach($campaign->fields(false) as $field)
                            <option value="{{ $field->name }}"{{ old('mobile_field', $campaign->mobile_field) == $field->name ? ' selected' : '' }}>{{ $field->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form__group form__select">
                        <label for="firstNameField">First Name Field</label>
                        <select name="first_name_field" id="firstNameField">
                            <option value="">Not Selected</option>
                            @foreach($campaign->fields(false) as $field)
                            <option value="{{ $field->name }}"{{ old('first_name_field', $campaign->first_name_field) == $field->name ? ' selected' : '' }}>{{ $field->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form__group form__select">
                        <label for="lastNameField">Last Name Field</label>
                        <select name="last_name_field" id="lastNameField">
                            <option value="">Not Selected</option>
                            @foreach($campaign->fields(false) as $field)
                            <option value="{{ $field->name }}"{{ old('last_name_field', $campaign->last_name_field) == $field->name ? ' selected' : '' }}>{{ $field->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form__submit">
                        <button type="submit" class="button button--large">Save Campaign</button>
                    </div>

                </form>

            </div>

        </div>

    </main>

</section>

@endsection