routes/web.php
<?php

use App\Http\Controllers\FrontController;
use App\Campaign;
use App\Client;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// temp putting this up here so it frickin works
Route::get('report/export/{report_id}', 'CampaignController@reportExport');
Route::get('report/{report_id}', 'CampaignController@report');

$zoos_routes = function () {

    // require functions
    $project_functions = dirname(__FILE__) . '/../public/assets/zoos-victoria_renew/functions.php';
    if(is_file($project_functions)) require_once($project_functions);

    $client_slug = 'zoos-victoria';
    $campaign_slug = 'renew';

    Route::post('send/{hash}', function ($hash) {
        $send = sendToFriends();
        return response()->json(true);
    });

    Route::post('video', function () {
        $videoUrl = renderVideo();
        return response()->json($videoUrl);
    });

    Route::get('/', function () use ($client_slug, $campaign_slug) {
        $front = new FrontController;
        return $front->primaryLanding($client_slug, $campaign_slug);
    });

    Route::get('member/{hash}', function ($hash) use ($client_slug, $campaign_slug) {
        $front = new FrontController;
        return $front->primaryLanding($client_slug, $campaign_slug, $hash);
    });

};

// ZOOS VIC ROUTES
Route::group(['domain' => 'zoos.vhx.host'], $zoos_routes);
Route::group(['domain' => 'zoos.mmrserver.com'], $zoos_routes);
Route::group(['domain' => 'renewforthezoo.org.au'], $zoos_routes);


// FRONT/LANDING (public)

//Route::auth();
Auth::routes();

Route::get('pw/{pw}', function ($pw) {
    return $pw . ':<br>' . '<textarea style="width:100%;" rows="50">' . bcrypt($pw) . '</textarea>';
});

Route::get('/{client}/{campaign}/', 'FrontController@primaryLanding');
Route::get('/{client}/{campaign}/register', 'FrontController@primaryLanding');
Route::get('/{client}/{campaign}/update/{hash}', 'FrontController@primaryLanding');
Route::get('/{client}/{campaign}/update/{hash}/{sendout}', 'FrontController@primaryLanding');
Route::post('/{client}/{campaign}/update/{hash}', 'FrontController@primaryProcess');
Route::get('/{client}/{campaign}/confirm/{hash}', 'FrontController@confirm');
Route::get('/{client}/{campaign}/confirm/{hash}/{sendout}', 'FrontController@confirm');
Route::get('/{client}/{campaign}/step-2/{hash}', 'FrontController@secondaryLanding');
Route::post('/{client}/{campaign}/step-2/{hash}', 'FrontController@secondaryProcess');
Route::get('/{client}/{campaign}/thanks/{hash}', 'FrontController@thanks');
Route::get('/{client}/{campaign}/thanks', 'FrontController@thanks');
Route::get('/{client}/{campaign}/update', 'FrontController@primaryLanding');
Route::post('/{client}/{campaign}/update', 'FrontController@primaryProcessNew');
Route::get('/{client}/{campaign}/page/{view}', 'FrontController@page');

// TEST URL
Route::get('/{client}/{campaign}/test/{view_file}/{field_key}/{field_value}', 'FrontController@testData');

Route::post('/link', 'FrontController@createShortUrl');

// DASHBOARD (private)

Route::get('/', 'CampaignController@home');


Route::get('home', 'CampaignController@home');

// campaigns
Route::get('campaigns', 'CampaignController@home');

// campaign responses
Route::get('/responses/send-out/{send_out}', 'HomeController@responses');
Route::get('/responses/field/{field_name}', 'CampaignController@responsesField');
Route::get('/responses/field/{field_name}/send-out/{send_out}', 'CampaignController@responsesField');
Route::get('/responses/compare/{field}', 'CampaignController@responsesCompare');
Route::get('/responses/compare/{field}/send-out/{send_out}', 'HomeController@responses_compare');
Route::get('/responses/record/{record_id}', 'CampaignController@responsesRecord');
Route::get('/responses', 'CampaignController@responses');

// campaign traffic
Route::get('/traffic/send-out/{send_out}', 'HomeController@traffic');
Route::get('/traffic', 'HomeController@traffic');

// campaign data
//Route::get('/data/send-out/{send_out}', 'CampaignController@data');
Route::get('/data', 'CampaignController@data');
Route::get('/data/table', 'CampaignController@dataTable');

// campaigns
Route::get('clients', 'AdminController@clients');
Route::get('client/edit/{client_id}', 'AdminController@editClient');

// reports
Route::get('reports', 'CampaignController@reports');

// admin
//Route::get('/admin/campaigns', 'AdminController@campaigns');

// REST

// campaigns
Route::get('campaign/set/{campaign_id}', 'CampaignController@set');
Route::get('campaign/set/{campaign_id}/{redirect}', 'CampaignController@set');
Route::get('overview/send-out/{send_out}', 'CampaignController@overview');
Route::get('overview', 'CampaignController@overview');
Route::get('overview/{campaign_id}/refresh', 'CampaignController@refreshOverview');
Route::get('responses/{campaign_id}/refresh', 'CampaignController@refreshFieldStats');
Route::get('campaign/tables/create/input/{campaign_id}', 'CampaignController@createInputTable');
Route::get('campaign/tables', 'CampaignController@getTables');
Route::resource('campaign', 'CampaignController');
Route::resource('campaign.fields', 'CampaignFieldController');
Route::resource('campaign.tables', 'CampaignTableController');

Route::get('overview/{campaign_id}/analytics', 'CampaignController@analytics');
Route::get('overview/{campaign_id}/results', 'CampaignController@results');

// sendouts
Route::resource('send-out', 'SendoutController');
Route::get('send-out/campaign/{campaign_id}', 'SendoutController@index');
Route::get('campaign/{campaign_id}/send-outs', 'SendoutController@home');

//Auth
Route::get('/logout', function () {
    Auth::logout();
    return redirect('/login');
});

Route::get('file', 'fileController@index');
 Route::get('save', 'fileController@save');

 

resources/views/admin/__campaigns.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">Campaigns</div>
    <div class="section-header__controls">
        <a href="{{ url('admin/campaigns/create') }}" class="button">New Campaign</a>
    </div>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">
        <h1 class="main__body__title">All Campaigns</h1>
        <div class="main__body__inner" id="campaignsViewAdmin"></div>
    </main>

</section>

@endsection

resources/views/admin/_campaigns.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">&nbsp;</div>
    <div class="section-header__controls">
        <a href="{{ url('admin/campaigns/create') }}" class="button">New Campaign</a>
    </div>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">

        <h1 class="main__body__title">Campaigns</h1>

        <div class="main__body__inner">

            <table class="table table--striped">

                <thead>
                    <tr>
                        <th>Client</th>
                        <th>Campaign</th>
                        <th>Created</th>
                    </tr>
                </thead>

                @foreach($campaigns as $campaign)
                <tr>
                    <td>{{ $campaign->client->name }}</td>
                    <td>{{ $campaign->name }}</td>
                    <td>{{ $campaign->created_at }}</td>
                </tr>
                @endforeach

            </table>


        </div>

    </main>

</section>

@endsection

resources/views/admin/campaigns.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">Campaigns</div>
    @can('mmr-admin')
    <div class="section-header__controls">
        <a href="{{ route('campaign.create') }}" class="button">New Campaign</a>
    </div>
    @endcan
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">
        <h1 class="main__body__title">All Campaigns</h1>
        <div class="main__body__inner">

            <table class="table table--striped">

                <thead>
                    <tr>
                        <th>Campaign</th>
                        <th>Client</th>
                        <th class="text-right">Emails Sent</th>
                        <th class="text-right">Recipients</th>
                        <th class="text-right">Responses</th>
                        <th class="text-right">Created</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach($campaigns as $campaign)
                    <tr>
                        <td>{{ $campaign->name }}</td>
                        <td><strong>{{ $campaign->client->name }}</strong></td>
                        <td class="text-right">{{ number_format($campaign->stats['recipients']['total'], 0, '.', ',') }}</td>
                        <td class="text-right">{{ number_format($campaign->stats['total_recipients']['total'], 0, '.', ',') }}</td>
                        <td class="text-right">{{ number_format($campaign->stats['responses']['total'], 0, '.', ',') }} ({{ $campaign->stats['responses']['%'] }})</td>
                        <td class="text-right">{{ $campaign->created_at }}</td>
                        <td class="text-right">
                            <a href="/campaign/set/{{ $campaign->id }}/overview" class="button button--small">Overview</a>
                            @can('mmr-admin')
                            <a href="/campaign/set/{{ $campaign->id }}/edit" class="button button--small">Edit</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach

                </tbody>

                @can('mmr-admin')
                <tfoot>
                    <tr>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th class="text-right">{{ number_format($totals['emails'], 0, '.', ',') }}</th>
                        <th class="text-right">{{ number_format($totals['recipients'], 0, '.', ',') }}</th>
                        <th class="text-right">{{ number_format($totals['responses'], 0, '.', ',') }} ({{ number_format(($totals['responses'] / $totals['recipients']) * 100, 0, '.', ',') }}%)</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                    </tr>
                </tfoot>
                @endcan

            </table>

        </div>
    </main>

</section>

@endsection

resources/views/admin/clients.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">Clients</div>
    @can('mmr-admin')
    <div class="section-header__controls">
        <a href="{{ url('admin/campaigns/create') }}" class="button">New Client</a>
    </div>
    @endcan
</div>

<section class="main">

    <main class="main__body">
        <h1 class="main__body__title">All Campaigns</h1>
        <div class="main__body__inner">

            <table class="table table--striped">

                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Campaigns</th>
                        <th>Campaign Monitor ID</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach($clients as $client)
                    <tr>
                        <td><strong>{{ $client->name }}</strong></td>
                        <td>{{ $client->slug }}</td>
                        <td>{{ $client->campaigns->count() }}</td>
                        <td>{{ $client->cm_client_id }}</td>
                        <td class="text-right">
                            @can('mmr-admin')
                            <a href="/client/edit/{{ $client->id }}" class="button button--small">Edit</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach

                </tbody>

            </table>

        </div>
    </main>

</section>

@endsection

resources/views/admin/report.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">Reports</div>
    <div class="section-header__controls">
        <a href="{{ url('report/export/' . $report->id) }}" class="button">Export</a>
    </div>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">
        <h1 class="main__body__title">{{ $report->name }} – {{ count($report_data) }} records</h1>

        <div class="data">

            <div class="data__main">

                <div class="data__table">

                    @if($report_data)
                    <table class="table table--striped">

                        <thead>
                            <tr>
                                @foreach($columns as $column)
                                <th>{{ $column }}</th>
                                @endforeach
                            </tr>
                        </thead>

                        <tbody>

                            @foreach($report_data as $row)
                            <tr>
                                @foreach($row as $column => $value)
                                <td>{{ $value }}</td>
                                @endforeach
                            </tr>
                            @endforeach

                        </tbody>

                    </table>
                    @else
                    <table class="table table--striped">
                        <tbody>
                            <tr>
                                <td>No data to show</td>
                            </tr>
                        </tbody>
                    </table>
                    @endif

                </div>

            </div>

        </div>

    </main>

</section>

@endsection

resources/views/admin/reports.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">Reports</div>
    <?php /*
    <div class="section-header__controls">
        <a href="{{ url('report/export/all') }}" class="button">Export All</a>
    </div>
    */ ?>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">
        <h1 class="main__body__title">All Reports</h1>
        <div class="main__body__inner">

            <table class="table table--striped">

                <thead>
                    <tr>
                        <th>Report</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach($reports as $report)
                    <tr>
                        <td><strong>{{ $report->name }}</strong></td>
                        <td class="text-right">
                            <a href="/report/{{ $report->id }}" class="button button--small">View</a>
                        </td>
                    </tr>
                    @endforeach

                </tbody>

            </table>

        </div>
    </main>

</section>

@endsection

resources/views/admin/send-outs.blade.php
@extends('layouts.app')

@section('content')

<div class="section-header">
    <div class="section-header__title">{{ $campaign->client->name }} - {{ $campaign->name }}</div>
    <div class="section-header__controls">
        <a href="{{ url('admin/campaigns/create') }}" class="button">New Send Out</a>
    </div>
</div>

<section class="main">

    @if($nav->show)
        @include('includes.sidebar-nav')
    @endif

    <main class="main__body">
        <h1 class="main__body__title">Send Outs</h1>
        <div class="main__body__inner" id="sendOutsView" data-campaign="{{ $campaign->id }}"></div>
    </main>

</section>

@endsection